// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2FhFQFuJ8LUdnoIVpyYIxazVJa33XMKE',
    appId: '1:276876339898:web:ad32a7b591f5bc4bfbb083',
    messagingSenderId: '276876339898',
    projectId: 'advocate-8dd7d',
    authDomain: 'advocate-8dd7d.firebaseapp.com',
    storageBucket: 'advocate-8dd7d.appspot.com',
    measurementId: 'G-689G4W1SX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCShjz3r-D5umq4WtQj8roXcjvCAI3LmBc',
    appId: '1:276876339898:android:7e5f12ef6f578c16fbb083',
    messagingSenderId: '276876339898',
    projectId: 'advocate-8dd7d',
    storageBucket: 'advocate-8dd7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4WLbL_t_4XuzncTHI-m9vfwBKxOA-fY',
    appId: '1:276876339898:ios:541bda6d20302ab7fbb083',
    messagingSenderId: '276876339898',
    projectId: 'advocate-8dd7d',
    storageBucket: 'advocate-8dd7d.appspot.com',
    iosClientId: '276876339898-skmj5njo2dpoajd5gic3h77fd9bcaqtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.advocate',
  );
}
